version: 2.1

jobs:
  backend-test:
    working_directory: /go/src/github.com/jitsucom/eventnative/
    docker:
      - image: circleci/golang:1.14
      - image: yandex/clickhouse-server:20.3
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    environment:
      PG_TEST_PORT: 5432
      CH_TEST_PORT: 8123
      TEST_RESULTS: /tmp/test-results
      GO111MODULE: "on"
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test_backend | tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: /tmp/test-results
      - run: go mod tidy
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  build-latest-docker:
    working_directory: /go/src/github.com/jitsucom/eventnative/
    environment:
      IMAGE_NAME: ksense/eventnative
    docker:
      - image: circleci/golang:1.14-buster-node
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Build and Push Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $IMAGE_NAME
  build-beta-docker:
    working_directory: /go/src/github.com/jitsucom/eventnative/
    environment:
      IMAGE_NAME: ksense/eventnative
    docker:
      - image: circleci/golang:1.14-buster-node
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Build and Push Docker image
          command: |
            docker build -t $IMAGE_NAME:beta .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $IMAGE_NAME
  build-tagged-docker:
    working_directory: /go/src/github.com/jitsucom/eventnative/
    environment:
      IMAGE_NAME: ksense/eventnative
    docker:
      - image: circleci/golang:1.14-buster-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker image
          command: |
            docker build -t $IMAGE_NAME:${CIRCLE_TAG//v} .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $IMAGE_NAME:${CIRCLE_TAG//v}

workflows:
  version: 2.1
  build-docker:
    jobs:
      - backend-test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build-latest-docker:
          context: eventnative
          requires:
            - backend-test
          filters:
            branches:
              only: master
      - build-beta-docker:
          context: eventnative
          requires:
            - backend-test
          filters:
            branches:
              only: beta
      - build-tagged-docker:
          context: eventnative
          requires:
            - backend-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/