server:
  name: jitsu
  disable_welcome_page: true
  strict_auth_tokens: true
  admin_token: '${env.CLUSTER_ADMIN_TOKEN|env.SERVER_ADMIN_TOKEN|demo___please_provide_value_in_production___}'
  telemetry: '${env.TELEMETRY_URL|}'

geo:
  maxmind_path: '${env.MAX_MIND_PATH|}'

geo_resolvers: '${env.GEO_RESOLVERS_URL|}'

api_keys: '${env.API_KEYS_URL|}'

destinations: '${env.DESTINATIONS_URL|}'

sources: '${env.SOURCES_URL|}'

system: '${env.SYSTEM_URL|}'

notifications:
  slack:
    url: '${env.SLACK_NOTIFICATIONS_WEBHOOK|}'

users_recognition:
  enabled: '${env.USER_RECOGNITION_ENABLED|false}'
  redis:
    host: '${env.USER_RECOGNITION_REDIS_URL|}'
    tls_skip_verify: '${env.TLS_SKIP_VERIFY|false}'

meta:
  storage:
    redis:
      host: '${env.REDIS_URL|}'
      tls_skip_verify: '${env.TLS_SKIP_VERIFY|false}'

events:
  queue:
    redis:
      host: '${env.EVENTS_QUEUE_REDIS_URL|}'
      tls_skip_verify: '${env.TLS_SKIP_VERIFY|false}'

coordination:
  type: redis

sql_debug_log:
  ddl:
    enabled: '${env.SQL_DDL_LOG_ENABLED|true}'
  queries:
    enabled: '${env.SQL_QUERIES_LOG_ENABLED|false}'

singer-bridge:
  log:
    enabled: '${env.SINGER_LOG_ENABLED|false}'

google-ads:
  developer-token: '${env.GOOGLE_ADS_DEVELOPER_TOKEN|}'
