name: Continuous Integration

on:
  # pull_request:
  push:
    branches: [master, beta]

jobs:
  frontend-check:
    runs-on: ubuntu-latest

    env:
      working-directory: ./configurator/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
        name: '[Configurator Front] installing packages (yarn install)'
        working-directory: ./configurator/frontend
      - run: yarn build
        name: '[Configurator Front] building'
        working-directory: ./configurator/frontend
      - run: yarn all:check
        name: '[Configurator Front] running prettier & eslint checks'
        working-directory: ./configurator/frontend
      - name: Notify to Slack on Errors
        uses: rtCamp/action-slack-notify@v2.2.0
        if: ${{ failure() }}
        env:
          SLACK_CHANNEL: code-guard
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_WEBHOOK: ${{ secrets.SLACK_CODEGUARD_WEBHOOK }}
          SLACK_FOOTER: ''

