name: Frontend CI


on:
  push:
    branches: 
      - '**'
      
jobs:
  frontend-build-and-test:
    runs-on: ubuntu-latest

    env:
      working-directory: ./configurator/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
        name: "[Frontend CI] installing packages (yarn install)"
        working-directory: ./configurator/frontend
      - run: yarn build
        name: "[Frontend CI] building"
        working-directory: ./configurator/frontend
      - run: yarn all:check
        name: "[Frontend CI] running prettier & eslint checks"
        working-directory: ./configurator/frontend
      - name: Notify to Slack on Errors
        uses: rtCamp/action-slack-notify@v2.2.0
        if: ${{ failure() && (env.GITHUB_REF == 'beta' || env.GITHUB_REF == 'master' ) }}
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON_EMOJI: ðŸ‘¿
          SLACK_WEBHOOK: ${{ secrets.SLACK_CI_FRONTEND_WEBHOOK }}
          SLACK_FOOTER: ""
