name: Notifications

on:
  workflow_run:
    workflows:
      - "Backend CI"
      - "Frontend CI"
    branches:
      - github_action_experiments
      - master
      - beta
    types:
      - requested


jobs:
  experiments:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump Env context
        env:
          GITHUB_CONTEXT: ${{ toJSON(env) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      #      - name: Fail
      #        run: failhere

      - name: Check Previous status on this branch
        id: check-ci
        uses: LASER-Yi/workflow-status@v0.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: backend-ci.yml
          branch: ${{ github.ref_name }}

#      - name: Notify to Slack on Errors
#        uses: rtCamp/action-slack-notify@v2.2.0
#        if: ${{ failure() && (github.ref_name == 'github_action_experiments' || github.ref_name == 'beta' || github.ref_name == 'master' ) }}
#        env:
#          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
#          SLACK_ICON_EMOJI: ðŸ‘¿
#          SLACK_TITLE: ${{ job.status }} wokflow failure
#          SLACK_WEBHOOK: ${{ secrets.SLACK_ILDAR_WEBHOOK }}
#          SLACK_FOOTER: ""
#
#      - name: Notify to Slack on Success
#        uses: rtCamp/action-slack-notify@v2.2.0
#        if: ${{ success() && steps.check-ci.outputs.conclusion == 'failure' && (github.ref_name == 'github_action_experiments' || github.ref_name == 'beta' || github.ref_name == 'master' ) }}
#        env:
#          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
#          SLACK_ICON_EMOJI: âœ…
#          SLACK_TITLE: ${{ job.status }} wokflow restored
#          SLACK_WEBHOOK: ${{ secrets.SLACK_ILDAR_WEBHOOK }}
#          SLACK_FOOTER: ""
